a = int(input("Enter the 1st value : "))
b = int(input("Enter the 2nd value : "))
print("\nArithmetic Operations : \n")
print("Addition of ",a,"and ",b," (a+b)        : ",a+b)
print("\nSubstraction of ",a,"and ",b," (a-b)    : ",a-b)
print("\nMultiplication of ",a,"and ",b," (a*b)  : ",a*b)
print("\nDivision of ",a,"and ",b," (a/b)        : ",a/b)
print("\nFloor Division of ",a,"and ",b," (a//b) : ",a//b)
print("\nModulo of ",a,"and ",b," (a%b)          : ",a%b)
print("\nExponent of ",a,"and ",b," (a**b)       : ",a**b)
